//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DueFormSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartement
    {
        public string PRNNo { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
        public Nullable<int> Backlog { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<int> Pass { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
        public virtual tblYesNo tblYesNo { get; set; }
        public virtual tblYesNo tblYesNo1 { get; set; }
        public virtual tblYesNo tblYesNo2 { get; set; }
    }
}
