//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DueFormSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScholarship1
    {
        public string PRNNo { get; set; }
        public Nullable<decimal> ScholarshipRemFromCollege { get; set; }
        public Nullable<int> NumberofScholarship { get; set; }
        public Nullable<int> Authenticate { get; set; }
    
        public virtual tblStudent1 tblStudent { get; set; }
        public virtual tblYesNo1 tblYesNo { get; set; }
    }
}
