//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DueFormSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent1
    {
        public string PRNNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Caste { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public string Email { get; set; }
    
        public virtual tblAccountSection1 tblAccountSection { get; set; }
        public virtual tblBranch1 tblBranch { get; set; }
        public virtual tblCaste1 tblCaste { get; set; }
        public virtual tblDepartement1 tblDepartement { get; set; }
        public virtual tblGender1 tblGender { get; set; }
        public virtual tblGym1 tblGym { get; set; }
        public virtual tblHostel1 tblHostel { get; set; }
        public virtual tblLibrary1 tblLibrary { get; set; }
        public virtual tblScholarship1 tblScholarship { get; set; }
        public virtual tblStudentSection1 tblStudentSection { get; set; }
        public virtual tblTPO1 tblTPO { get; set; }
    }
}
