//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DueFormSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentSection1
    {
        public string PRNNo { get; set; }
        public Nullable<int> Backlog { get; set; }
        public Nullable<int> PendingFee { get; set; }
        public Nullable<int> PendingProject { get; set; }
        public Nullable<int> CheckDue { get; set; }
    
        public virtual tblStudent1 tblStudent { get; set; }
        public virtual tblYesNo1 tblYesNo { get; set; }
        public virtual tblYesNo1 tblYesNo1 { get; set; }
        public virtual tblYesNo1 tblYesNo2 { get; set; }
    }
}
