//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DueFormSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public string PRNNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Caste { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public string Email { get; set; }
    
        public virtual tblAccountSection tblAccountSection { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCaste tblCaste { get; set; }
        public virtual tblDepartement tblDepartement { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblGym tblGym { get; set; }
        public virtual tblHostel tblHostel { get; set; }
        public virtual tblLibrary tblLibrary { get; set; }
        public virtual tblScholarship tblScholarship { get; set; }
        public virtual tblStudentSection tblStudentSection { get; set; }
        public virtual tblTPO tblTPO { get; set; }
    }
}
